### ISSUE TITLE
Exception using Python 3

### ISSUE THREAD

**Issue by brosl** [activescott/dbcexplode#2]
Using Python 3.6.9 the following error occurred while running the script:

```bash
  File "dbcexplode.py", line 46
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```
However, it ran successfully using Python 2.7.17

**Comment by strycker** [comment]
I had the same issue.  Script works with Python 2.7 though, so I used conda to downgrade my Python for a 1-time run.

**Comment by activescott** [comment]
@brosl @strycker I just made an update to make this work for python3 as well as a shebang so you can now run it like 
```
$ ./dbcexplode.py 20161003a.dbc
```

or
```
$ python3 ./dbcexplode.py 20161003a.dbc
```

**Comment by strycker** [comment]
Works now, thanks!
